import Head from "next/head";
import Image from "next/image";

import { Box, Flex } from "@chakra-ui/react";
import InsertionForm from "../components/InsertionForm";
import { UsersList } from "../components/UsersList";

export default function Home() {
  return (
    /**
     * {[sm,md,lg,xl]}
     */
    <Box
      h={[null, null, "100vh"]}
      w="100%"
      flexDir={["row", "row", "row"]}
      overflow="hidden"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* --- Insertion Form --- */}
      <InsertionForm />

      {/* --- Users List --- */}
      <UsersList />
    </Box>
  );
}
